---
name:                hledger-locker
version:             0.1.0.0
github:              "ShrykeWindgrace/hledger-locker"
license:             GPL-3
author:              "ShrykeWindgrace"
maintainer:          "shryke.windgrace@gmail.com"
copyright:           "2022 ShrykeWindgrace"

extra-source-files:
- README.md
- ChangeLog.md
- LICENSE

description:         Please see the README on GitHub at <https://github.com/ShrykeWindgrace/hledger-locker#readme>

dependencies:
  - base >= 4.7 && < 5
  
ghc-options:
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wmissing-fields
    - -Wmissing-deriving-strategies
    - -fwrite-ide-info
    - -hiedir=.hie
    - -Wall
    - -Wunused-packages
      
default-extensions:
  - DerivingStrategies
  - StrictData
  - FlexibleInstances
  - OverloadedStrings


library:
  source-dirs: src
  dependencies:
    - hledger-lib
    - directory
    - filepath
    - gitrev
    - co-log-core
    - colourista
    - mtl
    - transformers
    - selective
    - text
    - time
    - megaparsec >= 9
executables:
  hlocker:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hledger-locker
    - optparse-applicative
    - text
    - selective
    - mtl

tests:
  hledger-locker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hledger-locker
    - hspec
    - hspec-megaparsec
    - megaparsec
    - time
