name:                hledger-locker
version:             0.1.0.0
github:              "githubuser/hledger-locker"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hledger-locker#readme>

dependencies:
  - base >= 4.7 && < 5
  - co-log-core
  - colourista
  - megaparsec
  - mtl
  - transformers
  - selective
  - text
  - time
ghc-options:
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -Wmissing-fields
    - -Wmissing-deriving-strategies
    - -fwrite-ide-info
      
default-extensions:
  - DerivingStrategies
  - StrictData
  - FlexibleInstances
  - OverloadedStrings


library:
  source-dirs: src
  dependencies:
    - hledger-lib
    - directory
    - filepath
executables:
  hlocker:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hledger-locker

tests:
  hledger-locker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hledger-locker
    - hspec
    - hspec-megaparsec
    - hledger-lib
    - time
    - megaparsec
